# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "Eldius/linux-amzn2"
  config.vm.box_version = "0"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL

    function update_instance() {
      echo "#################################"
      echo "#        UPDATING SYSTEM        #"
      echo "#################################"
      sudo yum -y update
      echo "#################################"
      echo "#################################"
      echo ""
    }

    update_instance

  SHELL
end
